### PR TITLE
Updated the Contributors List in README.md

### PR DESCRIPTION
**Pull request by adithya-menon-r**
Hey @Ashrockzzz2003, I have added myself and @akshayks13 to the contributors list in `README.md` as requested.

### CODE REVIEW

**Review by Ashrockzzz2003 — CHANGES_REQUESTED** [review]
dei
ppl are ordered by language. Please follow the pattern.

**Comment by adithya-menon-r** [comment]
@Ashrockzzz2003 Very sorry about that... I have fixed it.

**Comment by akshayks13** [comment]
> Hey @Ashrockzzz2003, I have added myself and @akshayks13 to the contributors list in `README.md` as requested.

Thanks @adithya-menon-r  for including my name as well

**Review by Ashrockzzz2003 — APPROVED** [review]
LGTM

**Pull request merged**
