### PR TITLE
Update .gitignore

### LINKED ISSUE #4: Remove `.DS_Store` files from the repo and add it to `.gitignore`.
- [ ] Remove `.DS_Store` files from the repo.
- [ ] Add it to `.gitignore`.

This issue is meant explicitly for `1st years` participating in WOC.

### PR DESCRIPTION
**Pull request by BIJJUDAMA**
The changes have been made

Resolved #4

### CODE REVIEW

**Review by Ashrockzzz2003 — CHANGES_REQUESTED** [review]
Delete existing `.DS_Store` files from the repo.

**Comment by BIJJUDAMA** [comment]
@Ashrockzzz2003 Done
Deleted exisiting .DS_Store from the repo
Please review :)

**Comment by BIJJUDAMA** [comment]
Done @Ashrockzzz2003

**Review by Ashrockzzz2003 — CHANGES_REQUESTED** [review]
`.DS_Store` still exists inside `/non_linear/.DS_Store`. Remove them too.

**Review by Ashrockzzz2003 — CHANGES_REQUESTED** [review]
@BIJJUDAMA 
Why are binary values inside `.gitignore`
image

**Comment by BIJJUDAMA** [comment]
@Ashrockzzz2003  Can you please check now?
I don't see any binary values from my side now

**Review by Ashrockzzz2003 — CHANGES_REQUESTED** [review]
image

Two vals still there. 
Try this

1. Copy the first 2 lines needed for `.gitignore`
2. Delete the `.gitignore`
3. Create new file `.gitignore`
4. Commit and Push

This should fix. And please all this in 1 commit.

**Comment by BIJJUDAMA** [comment]
@Ashrockzzz2003 Can you check now?
Its now showing 2 lines like it should

**Review by Ashrockzzz2003 — APPROVED** [review]

**Comment by Ashrockzzz2003** [comment]
LGTM
Thanks for the contribution @BIJJUDAMA

**Comment by BIJJUDAMA** [comment]
Thanks for the support
As a first year its been a nice learning oppurtunity

**Comment by Ashrockzzz2003** [comment]
Check leaderboard!
You're now `No 2`.

**Pull request merged**
