### PR TITLE
Added c++ implementation of huffmann algorithm for generic classes

### PR DESCRIPTION
**Pull request by WinterSun23**
"Implemented generic Huffman encoding/decoding algorithm with customizable comparator and support for arbitrary data types using C++ templates."

### CODE REVIEW

**Comment by Ashrockzzz2003** [comment]
Will be reviewed over the weekend @WinterSun23

**Comment by Ashrockzzz2003** [comment]
> @Ashrockzzz2003 As the PR will be reviewed only in the weekend, I will not be able to work on any other issue. Is it possible to have it reviewed sooner?

@WinterSun23 
More issues will come soon in many repos and the contest duration is 2 months. Please co-operate!!

**Review by mdxaasil — COMMENTED** [review]
@WinterSun23  Could you please add a destructor for ```HuffmanTree``` Class? 
Rest works well 👍

**Review by mdxaasil — APPROVED** [review]

**Comment by WinterSun23** [comment]
I already have one:

~HuffmannTree(){
        for_each(nodes.begin(), nodes.end(), [](HuffNode<T> *node){delete node;});
    }

**Comment by mdxaasil** [comment]
> I already have one:
> 
> ~HuffmannTree(){ for_each(nodes.begin(), nodes.end(), [](HuffNode *node){delete node;}); }

Yup. My bad, I missed the last commit. Check the updated comment, approved now.

**Comment by WinterSun23** [comment]
Thank you very much! Sorry for the trouble. Can I close this now?

**Comment by Ashrockzzz2003** [comment]
Bonus 10 points for generic implementation.

**Comment by Ashrockzzz2003** [comment]
Thanks for the review @mdxaasil!

**Comment by WinterSun23** [comment]
Thank you!

**Pull request merged**
