### PR TITLE
Updated Contributors list in README.md

### PR DESCRIPTION
**Pull request by tharun-0106**
The README file has been updated to include the details of all contributors, ensuring proper acknowledgment of their efforts.

### CODE REVIEW

**Review by Ashrockzzz2003 — CHANGES_REQUESTED** [review]
Thanks a ton @tharun-0106 
Please do add @FirefoxSRV and @VishalTheHuman as Code Reviewers in README!

**Comment by tharun-0106** [comment]
@Ashrockzzz2003 the requested changes have been done.

**Review by Ashrockzzz2003 — CHANGES_REQUESTED** [review]
Please move Shreyas and Vishal above to after Aasil.
Add `Code Review` to aasil n me too!

**Comment by tharun-0106** [comment]
Made the required changes @Ashrockzzz2003

**Review by Ashrockzzz2003 — APPROVED** [review]
LGTM

**Comment by tharun-0106** [comment]
Thank you @Ashrockzzz2003

**Pull request merged**
